#
# @see https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
#

service: <%= name %>

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  stage: ${opt:stage}


# NOTE: This doesn't act quite like serverless, which adds a ** to the start of your globs which
# massively slows down globbing. By default everything is excluded. See ./scripts/bundle.js for details.
package:
  include:
    - node_modules/**
    - dist/**
    - prod.js
    - dev.js
    - package.json


functions:
  <% if(graphql) { %>
  graphql:
    handler: ${opt:stage}.graphqlApi
    events:
      - http:
          path: /
          method: post
          cors: true
  <% } else { %>
  demo:
    handler: ${opt:stage}.demo
    events:
      - http:
          path: /
          method: get
  <% } %>

#   Add any plugins here
plugins:
  - serverless-offline

